### ISSUE TITLE
Support downloading with own device id

### ISSUE THREAD

**Issue by swiftgeek** [rumboalla/apkupdater#19]
Please add support for downloading with own device id, instead of relying on evozi service (which doesn't have nice record)
https://lekensteyn.nl/apk-downloader/
https://github.com/Lekensteyn/apk-downloader

**Comment by rancidfrog** [comment]
For device ID: https://github.com/onyxbits/dummydroid
> DummyDroid a simple tool for creating a mock-up Android hardware profile and uploading it to Google Play for the purpose of generating a new GSF ID. 
I believe it can parse build.prop and generate ID to match device.

Raccoon connects directly to Play Store to download apps:
It would be great to be able to download directly from play store, instead of going through and relying on 3rd party sites.
Google Play Crawler allows one to download apps from play store directly, example Raccoon: https://github.com/onyxbits/Raccoon/tree/master/src/main/java/com/akdeniz/googleplaycrawler

It works great on desktop using java-api, which should be adaptable for android app.
User will need to use google account, preferrably dummy account not tied to personal account

- https://github.com/onyxbits/Raccoon
- https://github.com/Akdeniz/google-play-crawler
- https://github.com/onyxbits/raccoon4/tree/master/src/main/java/com/akdeniz/googleplaycrawler

**Comment by rumboalla** [comment]
This is now implemented on the dev branch.

**Comment by rancidfrog** [comment]
```
.setGsfId("332840dd1f6fbcb7")
.setToken("xwTCN6FyGkcpTew5FcY5NqOchMjh5bV5u172U2hJELXLGcGXCpCFqJFlBpjjOWjeG3jDng.");+
```
?
