### ISSUE TITLE
Don't show notification when 0 updates are found. 

### ISSUE THREAD

**Issue by jessehouwing** [rumboalla/apkupdater#263]
Just got a noticication with '0 updates found' which isn't all that useful.

I'd like the app to be as silent as possible, that way it provides the best experience.

**Comment by Quipyowert2** [comment]
Did you try setting Notifications setting in APKUpdater to "If updates are available" rather than the default of Always? I think that might work. I was wondering the same thing myself as that notification about zero updates happens a lot when manually checking for app updates using this app over a wifi with a weak signal.
