### ISSUE TITLE
Giving update to previous update to Previous version. (See app version in ss below)

### ISSUE THREAD

**Issue by AadilGillani** [rumboalla/apkupdater#321]
![Screenshot_20200909-173326.png](https://user-images.githubusercontent.com/15800642/92601212-f91b0c80-f2c5-11ea-9e29-0042a20bc42c.png)

Please bro this is an amazing app please fix this issue. This is one of the best apps I have ever came across this year.

**Comment by medlir** [comment]
There doesn't seem to be anything actually wrong here.  If you look at the versionCodes, rather then versionNames, the updates are all higher versionCode values.  The versionName values (the pretty x.y.z) are only for display purposes to users, and do make it SEEM wrong because it appears to be a previous version, but for purposes of update checking/updating, everything is supposed to look at versionCode, as versionName can be any arbitrary string.

https://developer.android.com/studio/publish/versioning

For MX Player Pro, your versionCode of 1310001245 is less than the update versionCodes of 1330001235 and 1330001244.

Likewise for Facebook Messenger, your v283.0.0.0.29 has a versionCode of 243783423, while v282.0.0.2.119 on APKMIrror has a versionCode of 243803180, and 243783423 < 243803180 so it's an update as well.

Confusing for sure, but perfectly valid, and that's how developers can also get people to "update" to an older version when there's a problem with a newer version, or sometimes they'll a re-release with an updated versionCode but the SAME versionName making it LOOK like an update to the same version you already have if you only look at the versionName.

**Comment by Bluscream** [comment]
> Please bro this is an amazing app please fix this issue. This is one of the best apps I have ever came across this year.

Try APKGrabber
