### ISSUE TITLE
Builds 545/547 Identified As Harmful

### ISSUE THREAD

**Issue by DmitryN71** [rumboalla/apkupdater#558]
![Screenshot_20240522_083954_Google Play Store](https://github.com/rumboalla/apkupdater/assets/43031473/72592c8d-ab5c-4bdb-95cb-56e6236aeb50)
First, it happened with build 545, then the warning was gone.
Now it happened again with build 547.

**Comment by peat80** [comment]
Also had this. You can disable play protect and then reenable.
It does another check and the warning will be gone after that. 😂

**Comment by rumboalla** [comment]
Of course Google doesn't like the app. Closing this because there is nothing I can do about it.

**Comment by IzzySoft** [comment]
Still an ongoing thing. Goog's so-called "safe" browsing just marking our repo now, [see my toot here](https://floss.social/@IzzyOnDroid/115933278279426046). We've sent it for review, but Gemini(?) refused – I doubt a single human was involved with the review.

I'm recording such cases now, because they "come in packs". In case you're interested: https://gitlab.com/-/snippets/4909577

And no, we're not removing ApkUpdater from our repo. Google's own scanner marks it green, having no findings. Confused now? Welcome! But take a look at VirusTotal and check for yourself…
